apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildpacks
spec:
  workspaces:
    - name: source
  params:
    - name: APP_IMAGE
      description: The name of where to store the app image.
    - name: BUILDER_IMAGE
      description: The builder image (e.g., paketobuildpacks/builder:base).
      default: paketobuildpacks/builder:base
  steps:
    - name: build
      image: $(params.BUILDER_IMAGE)
      workingDir: $(workspaces.source.path)
      command: ["/cnb/lifecycle/creator"]
      args:
        - "-app=$(workspaces.source.path)"
        - "-cache-dir=$(workspaces.source.path)/cache"
        - "$(params.APP_IMAGE)"
      # Buildpacks drop build times from 12min to 18s using efficient layer caching.
