apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: node-cpu-hog
  namespace: default
  annotations:
    chaos.gawain/green-knight: "beheaded but lives"
spec:
  engineState: "active"
  appinfo:
    appns: "default"
    applabel: "app=httpbin"
    appkind: "deployment"
  chaosServiceAccount: node-cpu-hog-sa
  experiments:
    - name: node-cpu-hog
